### PR TITLE
Add Polychrom

### PR DESCRIPTION
**Pull request by mikhin**

### CODE REVIEW

**Comment by mikhin** [comment]
@jake-figma, hi! Could you please review this pull request?

**Review by akbarbmirza — APPROVED** [review]
LGTM

**Comment by akbarbmirza** [comment]
Hey @mikhin - would love to shout you out on LinkedIn or Twitter. If you have either of those accounts and would like to be shouted out - let me know!

**Comment by mikhin** [comment]
@akbarbmirza, aww, thank you so much for your support — it's much appreciated!

We have slowly started to familiarize the audience with Polychrom and the APCA methodology.

For example, Roman, the author of the idea and design of Polychrom, wrote a thread about updates in the latest version of the plugin:
- On Twitter - https://x.com/romanshamin_en/status/1709674967007195642?s=20
- On LinkedIn - https://www.linkedin.com/posts/roman-shamin_polychrom-figma-community-activity-7115449344345972736-K7iU

So, it is possible to use these posts :)

**Comment by mikhin** [comment]
@akbarbmirza, btw, I wrote a thread on what's going on under the hood of the Polychrom frontend:
- https://twitter.com/mikhin97959/status/1711342704406172109
- https://www.linkedin.com/pulse/frontend-polychrom-figma-plugin-element-background-search-yuri-mikhin/

If you find this interesting, I would be very honored if you would share it :)

**Pull request merged**
