### PR TITLE
Add Design Tokens 

### PR DESCRIPTION
**Pull request by kelbri10**
Add Design Tokens, a plugin that allows designers to export tokens to JSON format.

### CODE REVIEW

**Comment by kelbri10** [comment]
@akbarbmirza this is my first time doing a pull request, I hope everything looks good!

**Review by akbarbmirza — CHANGES_REQUESTED** [review]
@kelbri10 can you reorder the entry so that it is in alphabetic order in the category and add a space between the heading and the links to the repo, plug-in, etc? once those are included, I can merge this

**Comment by kelbri10** [comment]
updated the entry to reflect the changes

**Comment by kelbri10** [comment]
> @kelbri10 can you reorder the entry so that it is in alphabetic order in the category and add a space between the heading and the links to the repo, plug-in, etc? once those are included, I can merge this

Updated !

**Review by akbarbmirza — APPROVED** [review]
LGTM

**Comment by akbarbmirza** [comment]
@kelbri10 do you have twitter or linkedin? Would love to shout you out on both of those platforms later this week

**Comment by kelbri10** [comment]
Here's the link to my [linkedin](https://www.linkedin.com/in/kelsey-hughes/)! @akbarbmirza

**Pull request merged**
